[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = /dev/cu.usbserial-0001
monitor_port = /dev/cu.usbserial-0001
lib_deps =
    m5stack/M5Unified @ ^0.2.2
    https://github.com/stack-chan/m5stack-avatar.git
    knolleary/PubSubClient @ ^2.8
    bblanchon/ArduinoJson @ ^7
