#!/usr/bin/env python3
"""Regenerates firmware/include/portraits_data.h from the bundled
"1-bit dialogue portraits" pack (assets/1-bit dialogue portraits/x2
64x64px/*.png at the repo root - see that folder's license.txt for terms).

Run from anywhere; paths below are relative to this file, not the cwd:

    python3 firmware/tools/gen_portraits.py

_GROUPS below is the frame manifest: which numbered portrait files (1-225,
matching the filenames in x2 64x64px/) are frames of the same character, in
the pack's own frame order. The pack ships no such manifest, so this was
recovered automatically and then spot-checked by eye:

  1. Downsample each portrait to 8x8 grayscale (kills the per-frame dither
     noise in hair/clothes that makes a naive full-resolution pixel diff
     unusable - two frames of the same character differ there by a few
     hundred; two different characters differ by several thousand).
  2. Sum the absolute difference between consecutive portraits in that
     space; a new group starts wherever it jumps past ~1700 (there's a
     clean gap in the sorted diffs between ~1600 and ~1900 - nothing landed
     in between).
  3. Rendered contact sheets and eyeballed the grouping against several
     ranges (1-16, 108-123, 150-165, 195-225) - all matched frame-for-frame.

99 characters, 1-4 frames each, 225 files total. Re-run this whole process
(not just re-embed _GROUPS by hand) if the pack is ever replaced - the
threshold was tuned against this specific pack's dither pattern.
"""
import pathlib

from PIL import Image

SCRIPT_DIR = pathlib.Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent.parent
ASSET_DIR = REPO_ROOT / "assets" / "1-bit dialogue portraits" / "x2 64x64px"
OUT_PATH = SCRIPT_DIR.parent / "include" / "portraits_data.h"

W = H = 64
ROW_BYTES = (W + 7) // 8  # 8, since W is byte-aligned

# See the module docstring for how this was derived.
_GROUPS = [
    [1, 2], [3, 4], [5, 6, 7, 8], [9, 10, 11], [12, 13, 14, 15], [16, 17, 18],
    [19, 20, 21], [22, 23], [24, 25, 26], [27, 28, 29, 30], [31, 32],
    [33, 34], [35, 36, 37], [38, 39, 40], [41, 42], [43, 44, 45, 46],
    [47, 48], [49, 50, 51], [52, 53, 54], [55, 56], [57, 58], [59, 60],
    [61, 62], [63, 64], [65, 66], [67, 68], [69, 70], [71, 72], [73, 74],
    [75, 76], [77, 78], [79, 80], [81, 82], [83, 84], [85, 86], [87, 88],
    [89, 90], [91, 92, 93, 94], [95, 96, 97], [98, 99, 100, 101],
    [102, 103], [104, 105, 106, 107], [108, 109], [110, 111], [112],
    [113, 114, 115], [116, 117], [118, 119], [120, 121], [122, 123],
    [124, 125], [126, 127], [128, 129], [130, 131], [132, 133], [134, 135],
    [136, 137], [138, 139], [140, 141], [142, 143], [144, 145], [146, 147],
    [148, 149], [150, 151], [152, 153], [154, 155], [156], [157, 158],
    [159, 160], [161, 162], [163, 164, 165], [166, 167], [168, 169],
    [170, 171, 172], [173, 174], [175, 176, 177], [178, 179], [180, 181],
    [182, 183], [184, 185], [186, 187, 188], [189, 190], [191, 192],
    [193, 194], [195, 196], [197, 198, 199], [200, 201], [202, 203],
    [204, 205], [206, 207], [208, 209], [210, 211], [212, 213], [214, 215],
    [216, 217], [218, 219], [220, 221], [222, 223], [224, 225],
]


def pack_bits(portrait_num):
    """Packs one portrait PNG into LGFX's drawBitmap() format: 1bpp,
    MSB-first per byte, rows padded to a byte boundary - verified against
    LGFXBase::draw_bitmap() in M5GFX, and round-tripped pixel-for-pixel
    against the source art. A pixel is "on" (bit set, drawn in the fg
    color) wherever the source art is dark ink, so it renders as lit
    (white) linework on the OLED's black background - see portrait_face.h.
    """
    im = Image.open(ASSET_DIR / f"portrait {portrait_num}.png").convert("RGBA")
    bg = Image.new("RGBA", im.size, (255, 255, 255, 255))
    bg.paste(im, (0, 0), im)
    px = bg.convert("L").load()
    out = []
    for y in range(H):
        for b in range(ROW_BYTES):
            byte = 0
            for bit in range(8):
                x = b * 8 + bit
                on = 1 if (x < W and px[x, y] < 128) else 0
                byte = (byte << 1) | on
            out.append(byte)
    return out


def main():
    assert sum(len(g) for g in _GROUPS) == 225
    assert len(_GROUPS) == 99

    header = '''// Generated by firmware/tools/gen_portraits.py from the "1-bit dialogue
// portraits" pack (assets/1-bit dialogue portraits/x2 64x64px/*.png at the
// repo root; see that folder's license.txt for terms). Do not hand-edit -
// re-run the generator (see its module docstring for how the frame
// grouping below was derived) if the source pack changes.
#pragma once

#include <stdint.h>
#include <stddef.h>

namespace portraits {

constexpr int kWidth = 64;
constexpr int kHeight = 64;

'''
    lines = [header]

    char_frame_vars = []
    for ci, group in enumerate(_GROUPS):
        frame_vars = []
        for fi, portrait_num in enumerate(group):
            bits = pack_bits(portrait_num)
            varname = f"kFrame_{ci}_{fi}"
            hexes = ", ".join(f"0x{b:02x}" for b in bits)
            lines.append(f"static const uint8_t {varname}[] = {{{hexes}}};\n")
            frame_vars.append(varname)
        char_frame_vars.append(frame_vars)
    lines.append("\n")

    for ci, frame_vars in enumerate(char_frame_vars):
        joined = ", ".join(frame_vars)
        lines.append(f"static const uint8_t *const kChar_{ci}_frames[] = {{{joined}}};\n")
    lines.append("\n")

    lines.append("struct Portrait {\n")
    lines.append("  const uint8_t *const *frames;\n")
    lines.append("  uint8_t frameCount;\n")
    lines.append("};\n\n")
    lines.append("static const Portrait kPortraits[] = {\n")
    for ci, frame_vars in enumerate(char_frame_vars):
        lines.append(f"    {{kChar_{ci}_frames, {len(frame_vars)}}},\n")
    lines.append("};\n\n")
    lines.append(
        "constexpr size_t kPortraitCount = sizeof(kPortraits) / sizeof(kPortraits[0]);\n\n"
    )
    lines.append("}  // namespace portraits\n")

    OUT_PATH.write_text("".join(lines))
    print(f"wrote {OUT_PATH}")
    print(f"characters: {len(_GROUPS)}, total frames: {sum(len(g) for g in _GROUPS)}")


if __name__ == "__main__":
    main()
